using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ConnectX.MessageRegister.SourceGenerator;

[Generator]
public sealed class ActorHandlerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidHandler = new(
        "CXACT001", "Invalid actor handler", "Actor handler '{0}' must be a non-static void/Task method with one MessageContext<T> parameter in a top-level, non-generic partial class",
        "ConnectX.Actors", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
            "ConnectX.Actors.ActorMessageAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol).Collect();
        context.RegisterSourceOutput(methods, static (output, handlers) =>
        {
            foreach (var group in handlers.GroupBy(m => m.ContainingType, SymbolEqualityComparer.Default))
            {
                var type = (INamedTypeSymbol)group.Key!;
                var ordered = group.OrderBy(m => m.Name, StringComparer.Ordinal).ToArray();
                var valid = true;
                foreach (var method in ordered)
                {
                    if (type.ContainingType != null || type.Arity != 0 || method.IsStatic || method.Arity != 0 ||
                        method.Parameters.Length != 1 || method.Parameters[0].RefKind != RefKind.None ||
                        method.Parameters[0].Type is not INamedTypeSymbol parameter ||
                        parameter.OriginalDefinition.ToDisplayString() != "Hive.Both.General.Dispatchers.MessageContext<T>" ||
                        (!method.ReturnsVoid && method.ReturnType.ToDisplayString() != "System.Threading.Tasks.Task") ||
                        !type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.Any(SyntaxKind.PartialKeyword)))
                    {
                        output.ReportDiagnostic(Diagnostic.Create(InvalidHandler, method.Locations.FirstOrDefault(), method.Name));
                        valid = false;
                    }
                }
                if (!valid) continue;
                var background = false;
                for (var parent = type.BaseType; parent != null; parent = parent.BaseType)
                    if (parent.ToDisplayString() == "Microsoft.Extensions.Hosting.BackgroundService") background = true;
                var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
                if (!type.ContainingNamespace.IsGlobalNamespace)
                    code.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(";\n");
                code.Append("partial class ")
                    .Append(type.Name).Append(" : global::System.IDisposable\n{\n")
                    .Append("private global::Hive.Both.General.Dispatchers.IDispatcher? _actorDispatcher;\n")
                    .Append("private readonly global::System.Collections.Generic.List<global::Hive.Both.General.Dispatchers.HandlerId> _actorHandlerIds = new();\n")
                    .Append("private void RegisterActorHandlers(global::Hive.Both.General.Dispatchers.IDispatcher dispatcher, global::ConnectX.Actors.ControlPlaneActor actor)\n{\n_actorDispatcher = dispatcher;\n");
                for (var i = 0; i < ordered.Length; i++)
                {
                    var message = ((INamedTypeSymbol)ordered[i].Parameters[0].Type).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    code.Append("_actorHandlerIds.Add(dispatcher.AddHandler<").Append(message).Append(">(ctx => { if (!actor.TryPost(new ActorCommand")
                        .Append(i).Append("(this, ctx))) global::ConnectX.Actors.SessionHealth.Close(ctx.FromSession); }));\n");
                }
                code.Append("}\npublic ").Append(background ? "override " : "").Append("void Dispose()\n{\nif (_actorDispatcher != null) foreach (var id in _actorHandlerIds) _actorDispatcher.RemoveHandler(id);\n_actorHandlerIds.Clear();\n");
                if (background) code.Append("base.Dispose();\n");
                code.Append("}\n");
                for (var i = 0; i < ordered.Length; i++)
                {
                    var method = ordered[i];
                    var parameter = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    code.Append("private sealed class ActorCommand").Append(i).Append("(").Append(type.Name).Append(" owner, ")
                        .Append(parameter).Append(" context) : global::ConnectX.Actors.IActorCommand\n{\npublic ")
                        .Append(method.ReturnsVoid ? "" : "async ").Append("global::System.Threading.Tasks.ValueTask ExecuteAsync(global::System.Threading.CancellationToken cancellationToken)\n{\n")
                        .Append(method.ReturnsVoid ? "" : "await ").Append("owner.@").Append(method.Name).Append("(context);");
                    if (method.ReturnsVoid) code.Append("return global::System.Threading.Tasks.ValueTask.CompletedTask;");
                    code.Append("\n}\npublic void Fail(global::System.Exception exception) => global::ConnectX.Actors.SessionHealth.Close(context.FromSession);\n}\n");
                }
                code.Append("}\n");
                output.AddSource(type.ToDisplayString().Replace('.', '_') + ".ActorHandlers.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
            }
        });
    }
}
