<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="../ConnectX.Server/ConnectX.Server.csproj" />
    <ProjectReference Include="../ConnectX.Relay/ConnectX.Relay.csproj" />
    <ProjectReference Include="../ConnectX.Client.Relay/ConnectX.Client.Relay.csproj" />
    <ProjectReference Include="../ConnectX.MessageRegister.SourceGenerator/ConnectX.MessageRegister.SourceGenerator.csproj" />
    <Analyzer Include="../ConnectX.MessageRegister.SourceGenerator/bin/$(Configuration)/netstandard2.0/ConnectX.MessageRegister.SourceGenerator.dll" />
  </ItemGroup>
</Project>
